 export const employeesData = [
  { id: "U31842", name: "Alice Smith", email: "alice.smith@ust.com" },
  { id: "402311", name: "Bob Johnson", email: "bob.johnson@ust.com" },
  { id: "U92310", name: "Charlie Brown", email: "charlie.brown@ust.com" },
  { id: "834211", name: "David Wilson", email: "david.wilson@ust.com" },
  { id: "U54321", name: "Eva Taylor", email: "eva.taylor@ust.com" },
  { id: "331245", name: "Frank Davis", email: "frank.davis@ust.com" },
  { id: "U88210", name: "Grace Miller", email: "grace.miller@ust.com" },
  { id: "230144", name: "Hannah Anderson", email: "hannah.anderson@ust.com" },
  { id: "U74125", name: "Ian Jones", email: "ian.jones@ust.com" },
  { id: "119021", name: "Julia Brown", email: "julia.brown@ust.com" },
  { id: "U45210", name: "Kevin Wilson", email: "kevin.wilson@ust.com" },
  { id: "654334", name: "Laura Taylor", email: "laura.taylor@ust.com" },
  { id: "U12944", name: "Michael Smith", email: "michael.smith@ust.com" },
  { id: "345122", name: "Nina Williams", email: "nina.williams@ust.com" },
  { id: "U77820", name: "Oliver Johnson", email: "oliver.johnson@ust.com" },
  { id: "214533", name: "Priya Davis", email: "priya.davis@ust.com" },
  { id: "U55991", name: "Quinn Miller", email: "quinn.miller@ust.com" },
  { id: "902311", name: "Rhea Anderson", email: "rhea.anderson@ust.com" },
  { id: "U33099", name: "Sam Brown", email: "sam.brown@ust.com" },
  { id: "721044", name: "Tina Jones", email: "tina.jones@ust.com" },
  { id: "U11024", name: "Uma Wilson", email: "uma.wilson@ust.com" },
  { id: "633522", name: "Victor Taylor", email: "victor.taylor@ust.com" },
  { id: "U99024", name: "Wendy Davis", email: "wendy.davis@ust.com" },
  { id: "752930", name: "Xavier Williams", email: "xavier.williams@ust.com" },
  { id: "U22019", name: "Yara Smith", email: "yara.smith@ust.com" }
];